//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WS_CONVUNI_SOAP_DOTNET_CLIWEB.ServicioConvUni {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicioConvUni.IConvUniServices")]
    public interface IConvUniServices {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConvUniServices/CentigradoAFarenheit", ReplyAction="http://tempuri.org/IConvUniServices/CentigradoAFarenheitResponse")]
        double CentigradoAFarenheit(double c);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConvUniServices/CentigradoAFarenheit", ReplyAction="http://tempuri.org/IConvUniServices/CentigradoAFarenheitResponse")]
        System.Threading.Tasks.Task<double> CentigradoAFarenheitAsync(double c);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConvUniServices/CentigradoAKelvin", ReplyAction="http://tempuri.org/IConvUniServices/CentigradoAKelvinResponse")]
        double CentigradoAKelvin(double c);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConvUniServices/CentigradoAKelvin", ReplyAction="http://tempuri.org/IConvUniServices/CentigradoAKelvinResponse")]
        System.Threading.Tasks.Task<double> CentigradoAKelvinAsync(double c);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IConvUniServicesChannel : WS_CONVUNI_SOAP_DOTNET_CLIWEB.ServicioConvUni.IConvUniServices, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ConvUniServicesClient : System.ServiceModel.ClientBase<WS_CONVUNI_SOAP_DOTNET_CLIWEB.ServicioConvUni.IConvUniServices>, WS_CONVUNI_SOAP_DOTNET_CLIWEB.ServicioConvUni.IConvUniServices {
        
        public ConvUniServicesClient() {
        }
        
        public ConvUniServicesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ConvUniServicesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConvUniServicesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConvUniServicesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public double CentigradoAFarenheit(double c) {
            return base.Channel.CentigradoAFarenheit(c);
        }
        
        public System.Threading.Tasks.Task<double> CentigradoAFarenheitAsync(double c) {
            return base.Channel.CentigradoAFarenheitAsync(c);
        }
        
        public double CentigradoAKelvin(double c) {
            return base.Channel.CentigradoAKelvin(c);
        }
        
        public System.Threading.Tasks.Task<double> CentigradoAKelvinAsync(double c) {
            return base.Channel.CentigradoAKelvinAsync(c);
        }
    }
}
